### ISSUE TITLE
Can't send notifications from a Firebase hosted website

### ISSUE THREAD

**Issue by fweffort** [expo/exponent-server-sdk-node#15] opened 2017-12-02 13:56 UTC
I can't make the request at all from firebase hosted website

Failed to load https://exp.host/--/api/v2/push/send: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://expo.io' that is not equal to the supplied origin. Origin 'http://bla.com is therefore not allowed access.

```
   var expo = new Expo();
        let messages = [];
        messages.push({
            "to": to,
            "title": titulo,
           "body": message,
                "sound": "default",
                "priority": 'high',
        })
        let chunks = expo.chunkPushNotifications(messages);
        for (let chunk of chunks) {
            try {
              let receipts = await expo.sendPushNotificationsAsync(chunk);
              console.log("receipts",receipts);
            } catch (error) {
              console.error("error",error);
            }
        }
```
or even:
```
const PUSH_ENDPOINT = 'https://exp.host/--/api/v2/push/send';
        var to = "ExponentPushToken[" + pushkey + "]"
        
        var self =this
        axios({
            method: 'post',
            url: PUSH_ENDPOINT,
            data:{
                "to": to ,
                "title": title,
                "body": message,
                "sound": "default",
                "priority": 'high',
            },
            headers :{'accept': 'application/json',
                'accept-encoding': 'gzip, deflate',
                'content-type': 'application/json'}
        })
            .then(function (response) {
                if (response.data.err) {
                    alert(response.data.mensagem)
                    return
                } else {
                    //
                    return
                }
            })
            .catch(function (error) {
                console.log(error);
            });
```

Is this issue on my end?

**Comment by ide** [comment] 2017-12-04 07:47
If you're on the free Firebase plan, they don't allow making network requests to other websites (or at least that used to be the policy).

**Comment by subodhpareek18** [comment] 2017-12-23 11:59
Just to be clear, if my backend server is hosted on AWS or something, then do I need to care about firebase paid plan at all? Reading the documentation gave the impression that paid firebase plan is a pre-req for all scenarios:

> Note for Firebase: You must have a paid plan to send push notifications with this library. As Firebase's pricing page says, "The Spark plan allows outbound network requests only to Google-owned services."

But nowhere was it mentioned in the docs about this firebase integration in the sholw push notificatino setup.

**Comment by ide** [comment] 2017-12-24 23:27
This is a limitation on Firebase's side, not Expo's, and it's covered on one of Google Cloud / Firebase's webpages. Using AWS should be fine but you could read AWS's documentation to be sure.

Expo's server networking code is currently all at the HTTP layer and if it helps to read the code, this is where to look: https://github.com/expo/exponent-server-sdk-node/blob/master/src/ExpoClient.js#L134

I'm going to close this issue since I believe the issue is due to a constraint with Firebase (or other hosting services) and not with Expo specifically.

**Closed by ide** 2017-12-24 23:27 UTC
